# Generated by Django 2.0.3 on 2018-03-14 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_assignees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='app_user',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_application.app_user'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_application.app_user'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='assigned_to_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_application.project'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='ranked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking_application.app_user'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='ranked_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking_application.requirement'),
        ),
        migrations.AddField(
            model_name='project_assignees',
            name='assigned_to_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_application.project'),
        ),
        migrations.AddField(
            model_name='project_assignees',
            name='assigned_user',
            field=models.ManyToManyField(to='ranking_application.app_user'),
        ),
    ]
