# Generated by Django 2.0.3 on 2018-03-19 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_application', '0004_auto_20180319_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='app_user',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
