# Generated by Django 2.0.3 on 2018-03-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_application', '0008_project_owned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_owned_by',
            name='project_owner',
        ),
        migrations.AddField(
            model_name='project_owned_by',
            name='project_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_application.app_user'),
        ),
    ]
