# Generated by Django 2.0.3 on 2018-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_application', '0009_auto_20180320_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_owned_by',
            name='project_owner',
        ),
        migrations.AddField(
            model_name='project_owned_by',
            name='project_owner',
            field=models.ManyToManyField(null=True, to='ranking_application.app_user'),
        ),
    ]
