# Generated by Django 2.0.3 on 2018-03-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_application', '0011_auto_20180320_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='active_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_application.project'),
        ),
    ]
