# Generated by Django 2.0.3 on 2018-03-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_application', '0012_app_user_active_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='active_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranking_application.project'),
        ),
    ]
