# Generated by Django 2.0.3 on 2018-04-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_application', '0013_auto_20180322_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='id_in_project',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app_user',
            name='active_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranking_application.project'),
        ),
    ]
