# Generated by Django 2.0.3 on 2018-04-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_application', '0014_auto_20180403_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking_application.project'),
        ),
    ]
